/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_SAR_Seq_1.h"
#include "CapSense_1.h"
#include "CapSense_1_Control.h"
#include "CapSense_1_Filter.h"
#include "CapSense_1_Processing.h"
#include "CapSense_1_Sensing.h"
#include "CapSense_1_Structure.h"
#include "CapSense_1_Tuner.h"
#include "CapSense_1_Configuration.h"
#include "CapSense_1_SensingCSD_LL.h"
#include "CapSense_1_RegisterMap.h"
#include "I2C_Slave.h"
#include "I2C_Slave_I2C.h"
#include "I2C_Slave_PINS.h"
#include "I2C_Slave_I2C_PVT.h"
#include "I2C_Slave_PVT.h"
#include "I2C_Slave_BOOT.h"
#include "I2C_1.h"
#include "I2C_1_I2C.h"
#include "I2C_1_PINS.h"
#include "I2C_1_I2C_PVT.h"
#include "I2C_1_PVT.h"
#include "I2C_1_BOOT.h"
#include "Timer_1.h"
#include "Clock_1.h"
#include "isr_1.h"
#include "ADC.h"
#include "ADC_aliases.h"
#include "VolPlus_in.h"
#include "VolPlus_in_aliases.h"
#include "Mute_in.h"
#include "Mute_in_aliases.h"
#include "VolReduce_in.h"
#include "VolReduce_in_aliases.h"
#include "Em_EEPROM_1.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "ADC_SAR_Seq_1_intClock.h"
#include "CapSense_1_ISR.h"
#include "I2C_Slave_SCBCLK.h"
#include "I2C_Slave_sda.h"
#include "I2C_Slave_sda_aliases.h"
#include "I2C_Slave_scl.h"
#include "I2C_Slave_scl_aliases.h"
#include "I2C_Slave_SCB_IRQ.h"
#include "I2C_1_SCBCLK.h"
#include "I2C_1_sda.h"
#include "I2C_1_sda_aliases.h"
#include "I2C_1_scl.h"
#include "I2C_1_scl_aliases.h"
#include "I2C_1_SCB_IRQ.h"
#include "cy_em_eeprom.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyLFClk.h"

/*[]*/

