# THIS FILE IS AUTOMATICALLY GENERATED
# Project: E:\weiwancheng\E300-77\two\44444\Workspace01\test2.cydsn\test2.cyprj
# Date: Wed, 08 Jan 2020 00:53:14 GMT
#set_units -time ns
create_clock -name {CapSense_ModClk(FFB)} -period 10625 -waveform {0 5312.5} [list [get_pins {ClockBlock/ff_div_3}]]
create_clock -name {EZI2C_SCBCLK(FFB)} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/ff_div_0}]]
create_clock -name {CyILO} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {CapSense_ModClk} -source [get_pins {ClockBlock/hfclk}] -edges {1 255 511} [list]
create_generated_clock -name {EZI2C_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 3 7} [list]


# Component constraints for E:\weiwancheng\E300-77\two\44444\Workspace01\test2.cydsn\TopDesign\TopDesign.cysch
# Project: E:\weiwancheng\E300-77\two\44444\Workspace01\test2.cydsn\test2.cyprj
# Date: Wed, 08 Jan 2020 00:53:13 GMT
