# THIS FILE IS AUTOMATICALLY GENERATED
# Project: E:\weiwancheng\E300-77\two\66666\Workspace01\Design01.cydsn\Design01.cyprj
# Date: Fri, 20 Mar 2020 01:29:02 GMT
#set_units -time ns
create_clock -name {CapSense_1_ModClk(FFB)} -period 10625 -waveform {0 5312.5} [list [get_pins {ClockBlock/ff_div_3}]]
create_clock -name {I2C_1_SCBCLK(FFB)} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/ff_div_0}]]
create_clock -name {Clock_1(FFB)} -period 1000 -waveform {0 500} [list [get_pins {ClockBlock/ff_div_4}] [get_pins {ClockBlock/ff_div_5}]]
create_clock -name {LIN_1_IntClk(FFB)} -period 3250 -waveform {0 1625} [list [get_pins {ClockBlock/ff_div_1}]]
create_clock -name {CyILO} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {CapSense_1_ModClk} -source [get_pins {ClockBlock/hfclk}] -edges {1 255 511} [list]
create_generated_clock -name {I2C_1_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 3 7} [list]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/hfclk}] -edges {1 25 49} [list]
create_generated_clock -name {LIN_1_IntClk} -source [get_pins {ClockBlock/hfclk}] -edges {1 79 157} [list]


# Component constraints for E:\weiwancheng\E300-77\two\66666\Workspace01\Design01.cydsn\TopDesign\TopDesign.cysch
# Project: E:\weiwancheng\E300-77\two\66666\Workspace01\Design01.cydsn\Design01.cyprj
# Date: Fri, 20 Mar 2020 01:28:59 GMT
