/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "isr_1.h"
#include "Clock_1.h"
#include "BEEP.h"
#include "BEEP_aliases.h"
#include "LIN_EN.h"
#include "LIN_EN_aliases.h"
#include "Timer_1.h"
#include "I2C_1.h"
#include "I2C_1_I2C.h"
#include "I2C_1_PINS.h"
#include "I2C_1_I2C_PVT.h"
#include "I2C_1_PVT.h"
#include "I2C_1_BOOT.h"
#include "LIN_1.h"
#include "CapSense_1.h"
#include "CapSense_1_Control.h"
#include "CapSense_1_Filter.h"
#include "CapSense_1_Processing.h"
#include "CapSense_1_Sensing.h"
#include "CapSense_1_Structure.h"
#include "CapSense_1_Tuner.h"
#include "CapSense_1_Configuration.h"
#include "CapSense_1_SensingCSD_LL.h"
#include "CapSense_1_RegisterMap.h"
#include "PWM_BEEP.h"
#include "RESPlus_in.h"
#include "RESPlus_in_aliases.h"
#include "Crusie_in.h"
#include "Crusie_in_aliases.h"
#include "SETReduce_in.h"
#include "SETReduce_in_aliases.h"
#include "Em_EEPROM_1.h"
#include "WdtIsr.h"
#include "I2C_1_SCBCLK.h"
#include "I2C_1_sda.h"
#include "I2C_1_sda_aliases.h"
#include "I2C_1_scl.h"
#include "I2C_1_scl_aliases.h"
#include "I2C_1_SCB_IRQ.h"
#include "LIN_1_ISR.h"
#include "LIN_1_IntClk.h"
#include "LIN_1_SCB.h"
#include "LIN_1_SCB_SPI_UART.h"
#include "LIN_1_SCB_PINS.h"
#include "LIN_1_SCB_SPI_UART_PVT.h"
#include "LIN_1_SCB_PVT.h"
#include "LIN_1_SCB_BOOT.h"
#include "CapSense_1_ISR.h"
#include "LIN_1_SCB_tx.h"
#include "LIN_1_SCB_tx_aliases.h"
#include "LIN_1_SCB_rx.h"
#include "LIN_1_SCB_rx_aliases.h"
#include "cy_em_eeprom.h"
#include "LIN_Dynamic.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyLFClk.h"

/*[]*/

